SELECT DISTINCT(NMPI),TESTDATE,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Urgency') as Urgency,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_SBP') as SBP,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='0101Ext') as Potassium,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Respiratory') as Respiratory,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='1013Ext') as WBC,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Pulse') as Pulse,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_PredictedNote') as Note,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_PeriContmn') as Peritoneal_Contamination,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_ECG') as ECG,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Morbidity') as Predicted_Morbidity,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_BloodLoss') as Operative_Blood_Loss,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_NoProce') as Number_of_Procedures,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='1003Ext') as Haemoglobin,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Cardiac') as Cardiac,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Mortality') as Predicted_Mortality,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_PhysScore') as Physiology_Score,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_OprnSevScore') as Operative_Severity_Score,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='0102Ext') as Sodium,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_GCS') as GCS,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Age') as Age,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_Malignancy') as Malignancy,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='P_OprtnSeverity') as Operation_Severity,
(SELECT DISTINCT a.[RESULTTEXT] from [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] a where a.NMPI=b.NMPI and a.TESTDATE=b.TESTDATE and a.FIELDID='0104Ext') as Urea
FROM [WDHB_RAD_LAB].[eclair].[tPPOSSUM_Dataset] b;
