SELECT [NMPI]
      ,[FORMID]
      ,[TESTDATE]
      ,[CLINICIANCODE]
      ,[FIELDID]
      ,[FIELDNAME]
      ,[UNITOFMEASURE]
      ,[RESULTTEXT]
      ,[FORMTYPE]
      ,[ENTEREDBY]
      ,[Encounter]
      ,[Enc_date]
      ,[iPM_Encounter]
      ,[iPM_Admit_date]
      ,[iPM_discharge_date]
  FROM [WDHB_RAD_LAB].[eclair].[tDVTWELLS_Dataset];